apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    environment: dev
    tier: db
spec:
 replicas: 1
 selector:
   matchLabels:
    project: roboshop
    component: mongodb
    environment: dev
    tier: db
 template:
   metadata:
    labels:
      project: roboshop
      component: mongodb
      environment: dev
      tier: db
    spec:
      containers:
      - name: mongodb
        image: aravind527/mongodb:v1
        imagePullPolicy: Always
      readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
      livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: service
metadata:
  name: mongodb
  namespace: roboshop
spec: 
  selector:
    project: roboshop
    component: mongodb
    environment: dev
    tier: db
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017
     
 