apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshop
  region: us-east-1
managedNodeGroups:
- name: roboshop-dev
  instanceTypes: ["m5.large","c4.large","c5.large"]   #["t2.small", "t3.medium"]
  desiredCapacity: 3
  spot: true